rem Erases all user space (WEB UI, BCL programs) in a Barionet 50
rem Keeps the firmware

set EMPTY=..\update_rescue\empty.cob

@echo off
echo # Erasing WEB1...
tftp -i %1 put %EMPTY% WEB1
echo # Erasing WEB2...
tftp -i %1 put %EMPTY% WEB2
echo # Erasing WEB3...
tftp -i %1 put %EMPTY% WEB3
echo # Erasing WEB4...
tftp -i %1 put %EMPTY% WEB4
echo # Erasing WEB5...
tftp -i %1 put %EMPTY% WEB5
echo # Erasing WEB6...
tftp -i %1 put %EMPTY% WEB6
echo # Erasing WEB7...
tftp -i %1 put %EMPTY% WEB7
echo # Erasing WEB8...
tftp -i %1 put %EMPTY% WEB8
echo # Erasing WEB9...
tftp -i %1 put %EMPTY% WEB9
echo # Erasing WEB10...
tftp -i %1 put %EMPTY% WEB10
echo # Erasing WEB11...
tftp -i %1 put %EMPTY% WEB11
echo # Erasing WEB12...
tftp -i %1 put %EMPTY% WEB12
echo # Erasing WEB13...
tftp -i %1 put %EMPTY% WEB13
echo # Erasing WEB14...
tftp -i %1 put %EMPTY% WEB14
echo # Erasing WEB15...
tftp -i %1 put %EMPTY% WEB15
echo # Erasing WEB16...
tftp -i %1 put %EMPTY% WEB16
echo # Erasing WEB17...
tftp -i %1 put %EMPTY% WEB17
echo # Erasing WEB18...
tftp -i %1 put %EMPTY% WEB18
echo # Erasing WEB19...
tftp -i %1 put %EMPTY% WEB19
echo # Erasing WEB20...
tftp -i %1 put %EMPTY% WEB20
echo # Erasing WEB21...
tftp -i %1 put %EMPTY% WEB21
echo # Erasing WEB22...
tftp -i %1 put %EMPTY% WEB22
echo # Erasing WEB23...
tftp -i %1 put %EMPTY% WEB23
echo # Erasing done...
